// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function ConnectSSH(arg1, arg2) {
  return window['go']['main']['App']['ConnectSSH'](arg1, arg2);
}

export function CreateSessionProfile(arg1) {
  return window['go']['main']['App']['CreateSessionProfile'](arg1);
}

export function DeleteSessionProfile(arg1) {
  return window['go']['main']['App']['DeleteSessionProfile'](arg1);
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function DownloadLocalModel() {
  return window['go']['main']['App']['DownloadLocalModel']();
}

export function DownloadLocalModelWithProgress() {
  return window['go']['main']['App']['DownloadLocalModelWithProgress']();
}

export function GetShellState() {
  return window['go']['main']['App']['GetShellState']();
}

export function ImportSSHConfig(arg1) {
  return window['go']['main']['App']['ImportSSHConfig'](arg1);
}

export function LaunchSession(arg1) {
  return window['go']['main']['App']['LaunchSession'](arg1);
}

export function ListSFTPFiles(arg1, arg2) {
  return window['go']['main']['App']['ListSFTPFiles'](arg1, arg2);
}

export function NavigateSFTP(arg1, arg2) {
  return window['go']['main']['App']['NavigateSFTP'](arg1, arg2);
}

export function OpenSessionWindow() {
  return window['go']['main']['App']['OpenSessionWindow']();
}

export function ReadSFTPFile(arg1, arg2) {
  return window['go']['main']['App']['ReadSFTPFile'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveCloudProvider(arg1, arg2) {
  return window['go']['main']['App']['SaveCloudProvider'](arg1, arg2);
}

export function SaveSFTPFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSFTPFile'](arg1, arg2, arg3);
}

export function SelectAIProvider(arg1) {
  return window['go']['main']['App']['SelectAIProvider'](arg1);
}

export function SendSSHInput(arg1, arg2) {
  return window['go']['main']['App']['SendSSHInput'](arg1, arg2);
}

export function StartLocalModel() {
  return window['go']['main']['App']['StartLocalModel']();
}

export function CancelModelDownload() {
  return window['go']['main']['App']['CancelModelDownload']();
}
