// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sessions} from '../models';
import {app} from '../models';
import {sftp} from '../models';
import {settings} from '../models';
import {vault} from '../models';
import {securestorage} from '../models';

export function CancelModelDownload():Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function ConnectSSH(arg1:string,arg2:string):Promise<void>;

export function CreateSessionProfile(arg1:sessions.ProfileInput):Promise<void>;

export function DeleteSessionProfile(arg1:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadLocalModel():Promise<void>;

export function DownloadLocalModelWithProgress():Promise<void>;

export function DownloadSFTPFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function GetShellState():Promise<app.ShellState>;

export function GetSecureStorageStatus():Promise<securestorage.Status>;

export function ImportSSHConfig(arg1:string):Promise<Array<sessions.Profile>>;

export function LaunchSession(arg1:string):Promise<app.RuntimeSessionView>;

export function ListCloudModels(arg1:string,arg2:string):Promise<Array<string>>;

export function ListSFTPFiles(arg1:string,arg2:string):Promise<Array<sftp.FileEntry>>;

export function ListVaultSecrets(arg1:string):Promise<Array<vault.SecretNode>>;

export function ListVaultSecretsForProvider(arg1:string,arg2:string):Promise<Array<vault.SecretNode>>;

export function NavigateSFTP(arg1:string,arg2:string):Promise<Array<sftp.FileEntry>>;

export function OpenSessionWindow():Promise<void>;

export function OpenRDP(arg1:string,arg2:string):Promise<void>;

export function ReadSFTPFile(arg1:string,arg2:string):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveCloudProvider(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSFTPFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectAIProvider(arg1:string):Promise<void>;

export function SendSSHInput(arg1:string,arg2:string):Promise<void>;

export function SelectDownloadDirectory():Promise<string>;

export function SelectUploadFiles():Promise<Array<string>>;

export function StartLocalModel():Promise<void>;

export function UploadSFTPFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SendChatMessage(arg1:string):Promise<void>;

export function ClearChat():Promise<void>;

export function AcceptSSHHostKey(arg1:string):Promise<void>;

export function EnsureMasterPassword(arg1:string):Promise<void>;

export function UpdateSettings(arg1:settings.AppSettings):Promise<void>;
