// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function GetShellState() {
  return window['go']['main']['App']['GetShellState']();
}

export function LaunchSession(arg1) {
  return window['go']['main']['App']['LaunchSession'](arg1);
}
